[project]
name = "aoc_utils"
version = "0.1.0"
description = "Advent of Code Utility Functions"
authors = [{ name = "PepperLola" }]
requires-python = ">=3.9"
dependencies = [
    "cffi>=2.0.0",
    "numpy>=2.0.2",
    "pytest>=8.4.2",
]
